cargo-features = ["per-package-target"]

[package]
name = "package-a"
version = "0.1.0"
edition = "2021"
forced-target = "aarch64-apple-darwin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.11"
